services:
  - type: web
    name: mycontact-api
    rootDir: backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 8080
      - key: MONGO_URI            # mets l’URI Atlas
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL         # à remplir après 1er déploiement du frontend
        value: https://mycontact-web.onrender.com

  - type: static
    name: mycontact-web
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
